# Workflow file for slow tests & on multiple python versions
name: Integration tests
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:  # <-- can be triggered manually!

jobs:
  integration-tests:
    if: github.event.review.state == 'approved'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4      
      - name: Set up Conda environment from environment.yaml
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          auto-activate-base: false
          python-version: ${{ matrix.version }}  # this overwrites python version in environment.yaml
      - name: Install and run tests (Linux)
        if: runner.os == 'linux'
        uses: ./.github/actions/linux
      - name: Install and run tests (MacOS)
        if: runner.os != 'linux
        uses: ./.github/actions/windows-mac
